### ISSUE TITLE
Trinti gali bet kas per nuoroda.

### ISSUE THREAD

**Issue by kabalas2** [mancioks/il6_php#3]
https://github.com/mancioks/il6_php/blob/ab61d7abae0e73697a53170665b07c15daf592df/naujas/app/code/Controller/Catalog.php#L246

trinimas turetu buti relizuojamas tarkim prie edito kazkur migtukas ar panasiai, kad useris galetu istrinti savo skelbima, o dabar bota paleidus butu galima istrinti visus skelbimus. plius butu gerai relizuoti soft delete sitoje vietoje

**Comment by mancioks** [comment]
deletas is seniau uzsilikes, visai pamirsau apie ji nes dar vis nepanaudotas metodas, okey
