### ISSUE TITLE
itartinai atrodo... 

### ISSUE THREAD

**Issue by kabalas2** [mancioks/il6_php#6]
https://github.com/mancioks/il6_php/blob/ab61d7abae0e73697a53170665b07c15daf592df/naujas/app/code/Model/Ad.php#L262

**Comment by mancioks** [comment]
Gali but kad nera labai gerai, nes cia kraunu objekta pirmiau pagal slug, jei nera nei vieno iraso su tokiu slug -tada ta slug naudoju kaip id ir kraunu pagal id, cia pirmiem skelbimam kurie neturi slug.

**Comment by kabalas2** [comment]
Tai istrink tuos skelbimus arba sugeneruok jiem sluga. nes lugas turetu buti required.
