### ISSUE TITLE
O jei pagal email toks useris negrizo?

### ISSUE THREAD

**Issue by kabalas2** [mancioks/il6_php#7]
https://github.com/mancioks/il6_php/blob/ab61d7abae0e73697a53170665b07c15daf592df/naujas/app/code/Model/User.php#L187

**Comment by mancioks** [comment]
user controlleryje pirmiau tikrinu ar yra toks email, ir jei yra kvieciu sita metoda

**Comment by kabalas2** [comment]
o jei sita metoda naudosi kazkur kitur ir nebus pirma tikrinimo?:)

**Comment by mancioks** [comment]
Imeciau User modelyje kad uzloadintu tik tada jei isset user id pagal get is db pagal email. Ir taip gaunas, kad tas load nieko neuzloadina jei nera tokio email, tai cia butu tinkamas variantas? :D
https://github.com/mancioks/il6_php/commit/068de8908df0bda3388c85814e3aff66c243d238

**Comment by kabalas2** [comment]
taip, kazkur kode tikrinsi tada ar ne ampty ar panasiai, siuo atveju nereiks nes pirma su emailu jau pachekinai ar kaip ten
